.\" man page create by R# package system.
.TH ACTIVATEFUNCTION 1 2000-1月 "func" "func"
.SH NAME
func \- create a new custom activate function
.SH SYNOPSIS
\fIfunc(\fBforward\fR as any, 
\fBderivative\fR as any, 
\fBtruncate\fR as double = -1, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a new custom activate function
.PP
.SH OPTIONS
.PP
\fBforward\fB \fR\- -. 
.PP
.PP
\fBderivative\fB \fR\- 
 derivative formula of the \fB**`forward`**\fR formula
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
activateFunction
.SH FILES
.PP
enigma.dll
.PP
