.TH .AISHELL3_PINYIN 1 2025-Sep "" ".aishell3_pinyin"
.SH NAME
.aishell3_pinyin \- .aishell3_pinyin(pinyin.lib, si)
.SH SYNOPSIS
\fI.aishell3_pinyin(pinyin.lib, si)\fR
.SH OPTIONS
.PP
\fBpinyin.lib\fB \fR\- . 
.PP
.PP
\fBsi\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..aishell3_pinyin at pinyin.R:line 25
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
