.TH .PINYIN 1 2025-Jun "" ".pinyin"
.SH NAME
.pinyin \- .pinyin(pinyin.lib, si)
.SH SYNOPSIS
\fI.pinyin(pinyin.lib, si)\fR
.SH OPTIONS
.PP
\fBpinyin.lib\fB \fR\- . 
.PP
.PP
\fBsi\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..pinyin at pinyin.R:line 46
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
