.TH DATA_AISHELL3 1 2025-Jul "" "data_aishell3"
.SH NAME
data_aishell3 \- data_aishell3(text)
.SH SYNOPSIS
\fIdata_aishell3(text)\fR
.SH OPTIONS
.PP
\fBtext\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.data_aishell3 at pinyin.R:line 15
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2025
