.\" man page create by R# package system.
.TH MODEL 1 2000-Jan "readModelFile" "readModelFile"
.SH NAME
readModelFile \- load saved machine learning model
.SH SYNOPSIS
\fIreadModelFile(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
load saved machine learning model
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- A file path to the model snapshot data file.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
model
.SH FILES
.PP
enigma.dll
.PP
