.\" man page create by R# package system.
.TH MODEL 1 2000-Jan "snapshot" "snapshot"
.SH NAME
snapshot \- make the snapshot of the machine learning model
.SH SYNOPSIS
\fIsnapshot(\fBmodel\fR as <generic> MLModel, 
\fBfile\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
make the snapshot of the machine learning model
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- A machine learning model. 
.PP
.PP
\fBfile\fB \fR\- A file path value, the model snapshot will be save to this file.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
model
.SH FILES
.PP
enigma.dll
.PP
