.\" man page create by R# package system.
.TH MODEL 1 2000-1月 "svm" "svm"
.SH NAME
svm \- Support-vector machines
.SH SYNOPSIS
\fIsvm();\fR
.SH DESCRIPTION
.PP
Support-vector machines

 Support-vector machines (SVMs), also known as support-vector 
 networks, are a set of related supervised learning methods 
 used for classification And regression. Given a set of training 
 examples, each marked as belonging to one of two categories, 
 an SVM training algorithm builds a model that predicts whether 
 a New example falls into one category. An SVM training 
 algorithm Is a non-probabilistic, binary, linear classifier, 
 although methods such as Platt scaling exist to use SVM in a 
 probabilistic classification setting. In addition to performing
 linear classification, SVMs can efficiently perform a non-linear 
 classification using what Is called the kernel trick, 
 implicitly mapping their inputs into high-dimensional feature 
 spaces.
.PP
.SH SEE ALSO
model
.SH FILES
.PP
enigma.dll
.PP
