.\" man page create by R# package system.
.TH MODEL 1 2000-Jan "xgboost" "xgboost"
.SH NAME
xgboost \- XGBoost (eXtreme Gradient Boosting)
.SH SYNOPSIS
\fIxgboost();\fR
.SH DESCRIPTION
.PP
XGBoost (eXtreme Gradient Boosting)
 
 XGBoost is an optimized distributed gradient boosting library
 designed to be highly efficient, flexible and portable. 
 It implements machine learning algorithms under the Gradient
 Boosting framework. XGBoost provides a parallel tree boosting 
 (also known as GBDT, GBM) that solve many data science 
 problems in a fast and accurate way.
.PP
.SH SEE ALSO
model
.SH FILES
.PP
enigma.dll
.PP
