.\" man page create by R# package system.
.TH GPU 1 2000-Jan "exec" "exec"
.SH NAME
exec \- try to execute the expression on gpu
.SH SYNOPSIS
\fIexec(\fBexp\fR as <generic> Expression, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
try to execute the expression on gpu
.PP
.SH OPTIONS
.PP
\fBexp\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
gpu
.SH FILES
.PP
enigma.dll
.PP
