.\" man page create by R# package system.
.TH BOOTSTRAPPING 1 2000-Jan "complex" "complex"
.SH NAME
complex \- 
.SH SYNOPSIS
\fIcomplex(\fBargs\fR as <generic> Arguments, 
\fBalgorithm\fR as any = ["ComplEx","complex_NNE","complex_NNE_AER","complex_R"], 
\fBrules\fR as string = \fB<NULL>\fR, 
\fBiterations\fR as integer = 1000, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
bootstrapping
.SH FILES
.PP
enigma.dll
.PP
