.\" man page create by R# package system.
.TH LEARNING 1 2000-Jan "feed" "feed"
.SH NAME
feed \- feed training data to the machine learning model
.SH SYNOPSIS
\fIfeed(\fBmodel\fR as <generic> Model, 
\fBx\fR as any, 
\fBfeatures\fR as any, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
feed training data to the machine learning model
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
learning
.SH FILES
.PP
enigma.dll
.PP
