.\" man page create by R# package system.
.TH LEARNING 1 2000-1月 "hidden_layer" "hidden_layer"
.SH NAME
hidden_layer \- configs of the hidden layer of the \fB@\fRT:enigma.ANN```` model
.SH SYNOPSIS
\fIhidden_layer(\fBmodel\fR as <generic> ANN, 
\fBsize\fR as any, 
\fBactivate\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
configs of the hidden layer of the \fB@\fRT:enigma.ANN```` model
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- The \fB@\fRT:enigma.ANN```` machine learning model object. 
.PP
.PP
\fBsize\fB \fR\- A integer vector for configs the layer size in the hidden layer. 
.PP
.PP
\fBactivate\fB \fR\- Activation function of the hidden layer. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
learning
.SH FILES
.PP
enigma.dll
.PP
