.\" man page create by R# package system.
.TH LEARNING 1 2000-01-01 "hidden_layer" "hidden_layer"
.SH NAME
hidden_layer \- 
.SH SYNOPSIS
\fIhidden_layer(\fBmodel\fR as <generic> ANN, 
\fBsize\fR as any, 
\fBactivate\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
learning
.SH FILES
.PP
enigma.dll
.PP
