.\" man page create by R# package system.
.TH LEARNING 1 2000-Jan "learn" "learn"
.SH NAME
learn \- Do machine learning model training
.SH SYNOPSIS
\fIlearn(\fBmodel\fR as <generic> MLModel, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do machine learning model training
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBargs\fB \fR\- 
 the additional arguments to the machine learning model trainer, it could be:
 
 1. ANN model
 
 + truncate, numeric
 + threshold, numeric
 + parallel, logical
 + softmax, logical
 + max.epochs, integer
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
learning
.SH FILES
.PP
enigma.dll
.PP
