.\" man page create by R# package system.
.TH LEARNING 1 2000-Jan "output_layer" "output_layer"
.SH NAME
output_layer \- 
.SH SYNOPSIS
\fIoutput_layer(\fBmodel\fR as <generic> ANN, 
\fBlabels\fR as any = \fB<NULL>\fR, 
\fBactivate\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
learning
.SH FILES
.PP
enigma.dll
.PP
