.\" man page create by R# package system.
.TH LEARNING 1 2000-Jan "output" "output"
.SH NAME
output \- configs of the output layer of the \fB@\fRT:enigma.ANN```` model
.SH SYNOPSIS
\fIoutput(\fBmodel\fR as <generic> MLModel, 
\fBlabels\fR as any = \fB<NULL>\fR, 
\fBactivate\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
configs of the output layer of the \fB@\fRT:enigma.ANN```` model
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBlabels\fB \fR\- -. 
.PP
.PP
\fBactivate\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
learning
.SH FILES
.PP
enigma.dll
.PP
