.\" man page create by R# package system.
.TH LEARNING 1 2000-1月 "solve" "solve"
.SH NAME
solve \- Do data prediction
.SH SYNOPSIS
\fIsolve(\fBmodel\fR as <generic> MLModel, 
\fBdata\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do data prediction
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- 
 A machine learning model which is has been trained via the \fBlearn\fR function.
 Or this machine learning algorithm model also could be loaded from the snapshot 
 file via the \fBreadModelFile\fR.
. 
.PP
.PP
\fBdata\fB \fR\- 
 A dataframe object which should contains the same features fields with the 
 input training data
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
learning
.SH FILES
.PP
enigma.dll
.PP
