.\" man page create by R# package system.
.TH LEARNING 1 2000-Jan "trainTestSplit" "trainTestSplit"
.SH NAME
trainTestSplit \- Split a Dataset into Train and Test Sets
.SH SYNOPSIS
\fItrainTestSplit(\fBx\fR as <generic> dataframe, 
\fBtrain_ratio\fR as double = 0.8, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Split a Dataset into Train and Test Sets
 
 The train-test split is used to estimate the performance
 of machine learning algorithms that are applicable for 
 prediction-based Algorithms/Applications. This method is 
 a fast and easy procedure to perform such that we can 
 compare our own machine learning model results to machine
 results. By default, the Test set is split into 30 % of 
 actual data and the training set is split into 70% of the 
 actual data.
 
 We need To split a dataset into train And test sets To 
 evaluate how well our machine learning model performs. The
 train Set Is used To fit the model, And the statistics Of
 the train Set are known. The second Set Is called the test
 data Set, this Set Is solely used For predictions.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBtrain_ratio\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
learning
.SH FILES
.PP
enigma.dll
.PP
